//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mantenimientos
    {
        public int id_mantenimiento { get; set; }
        public int id_moto { get; set; }
        public int id_mecanico { get; set; }
        public Nullable<System.DateTime> fecha_recepcion { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public string motivo_cliente { get; set; }
        public string trabajo_realizado { get; set; }
        public Nullable<decimal> costo { get; set; }
    
        public virtual Mecanicos Mecanicos { get; set; }
        public virtual Motos Motos { get; set; }
    }
}
