//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int id_reserva { get; set; }
        public int id_cliente { get; set; }
        public int id_moto { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
        public Nullable<System.DateTime> fecha_limite { get; set; }
        public decimal importe_senal { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Motos Motos { get; set; }
    }
}
